USE [master]
GO

/****** Object:  Database [Riego]    Script Date: 1/11/2021 18:05:49 ******/
CREATE DATABASE [Riego]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Riego', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Riego.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Riego_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Riego_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Riego].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Riego] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Riego] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Riego] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Riego] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Riego] SET ARITHABORT OFF 
GO

ALTER DATABASE [Riego] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Riego] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Riego] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Riego] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Riego] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Riego] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Riego] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Riego] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Riego] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Riego] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Riego] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Riego] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Riego] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Riego] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Riego] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Riego] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Riego] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Riego] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Riego] SET  MULTI_USER 
GO

ALTER DATABASE [Riego] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Riego] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Riego] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Riego] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Riego] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Riego] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Riego] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Riego] SET  READ_WRITE 
GO

